services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin_password
    networks:
      - rabbitmq-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  rabbitmq-network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/matrix/Desktop/DockerVolumes/


# docker compose -f "docker-compose.yaml" up -d
