services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    network_mode: host # Use host network for direct access
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin_password
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      retries: 5
      start_period: 30s
      timeout: 10s


      
# docker compose -f "docker-compose.yaml" up -d
